export type ServiceArea = {
  name: string;
  counties: readonly string[];
  zipCodes: readonly string[];
};

export type ServiceAreaZip = {
  zipCode: string;
  communities: readonly string[];
  counties: readonly string[];
  group: string;
};

/**
 * Geographic center: South Houston, Texas (Census 2025 internal point
 * 29.661024, -95.228361). The repository does not publish a street address.
 *
 * Place names and radius checks: U.S. Census Bureau 2025 Gazetteer files.
 * ZIP/city names: USPS ZIP Code Lookup. ZIP/county relationships: HUD USPS
 * ZIP–County Crosswalk. PO-box-only and organization-only ZIPs are excluded
 * because they do not describe a serviceable property location.
 */
export const SERVICE_AREAS = [
  { name: "Ace", counties: ["Polk"], zipCodes: ["77326"] },
  { name: "Aldine", counties: ["Harris"], zipCodes: ["77037", "77039"] },
  { name: "Alvin", counties: ["Brazoria"], zipCodes: ["77511"] },
  { name: "Ames", counties: ["Liberty"], zipCodes: ["77575"] },
  { name: "Anahuac", counties: ["Chambers"], zipCodes: ["77514"] },
  { name: "Anderson", counties: ["Grimes"], zipCodes: ["77830"] },
  { name: "Angleton", counties: ["Brazoria"], zipCodes: ["77515"] },
  { name: "Arcola", counties: ["Fort Bend"], zipCodes: ["77583"] },
  { name: "Atascocita", counties: ["Harris"], zipCodes: ["77346"] },
  { name: "Bacliff", counties: ["Galveston"], zipCodes: ["77518"] },
  { name: "Bailey's Prairie", counties: ["Brazoria"], zipCodes: ["77515"] },
  { name: "Barrett", counties: ["Harris"], zipCodes: ["77532"] },
  { name: "Batson", counties: ["Hardin"], zipCodes: ["77519"] },
  { name: "Bay City", counties: ["Matagorda"], zipCodes: ["77414"] },
  { name: "Bayou Vista", counties: ["Galveston"], zipCodes: ["77563"] },
  { name: "Baytown", counties: ["Harris", "Chambers"], zipCodes: ["77520", "77521", "77523"] },
  { name: "Beach City", counties: ["Chambers"], zipCodes: ["77523"] },
  { name: "Beasley", counties: ["Fort Bend"], zipCodes: ["77417"] },
  {
    name: "Beaumont",
    counties: ["Jefferson"],
    zipCodes: ["77701", "77702", "77703", "77705", "77706", "77707", "77708", "77713"],
  },
  { name: "Bedias", counties: ["Grimes"], zipCodes: ["77831"] },
  { name: "Bellaire", counties: ["Harris"], zipCodes: ["77401"] },
  { name: "Bellville", counties: ["Austin"], zipCodes: ["77418"] },
  { name: "Bevil Oaks", counties: ["Jefferson"], zipCodes: ["77713"] },
  { name: "Blessing", counties: ["Matagorda"], zipCodes: ["77419"] },
  { name: "Boling", counties: ["Wharton"], zipCodes: ["77420"] },
  { name: "Bolivar Peninsula", counties: ["Galveston"], zipCodes: ["77650"] },
  { name: "Bonney", counties: ["Brazoria"], zipCodes: ["77583"] },
  { name: "Brazoria", counties: ["Brazoria"], zipCodes: ["77422"] },
  { name: "Brenham", counties: ["Washington"], zipCodes: ["77833"] },
  { name: "Bridge City", counties: ["Orange"], zipCodes: ["77611"] },
  { name: "Brookshire", counties: ["Waller", "Fort Bend"], zipCodes: ["77423"] },
  { name: "Brookside Village", counties: ["Brazoria"], zipCodes: ["77581"] },
  { name: "Burton", counties: ["Washington"], zipCodes: ["77835"] },
  { name: "Caldwell", counties: ["Burleson"], zipCodes: ["77836"] },
  { name: "Carmine", counties: ["Fayette"], zipCodes: ["78932"] },
  { name: "Cat Spring", counties: ["Austin", "Colorado"], zipCodes: ["78933"] },
  { name: "Cedar Lane", counties: ["Matagorda"], zipCodes: ["77415"] },
  { name: "Channelview", counties: ["Harris"], zipCodes: ["77530"] },
  { name: "Chappell Hill", counties: ["Washington"], zipCodes: ["77426"] },
  { name: "China", counties: ["Jefferson"], zipCodes: ["77613"] },
  { name: "Cinco Ranch", counties: ["Fort Bend", "Harris"], zipCodes: ["77450", "77494"] },
  {
    name: "Clear Lake area",
    counties: ["Harris", "Galveston"],
    zipCodes: ["77058", "77059", "77062"],
  },
  { name: "Clear Lake Shores", counties: ["Galveston"], zipCodes: ["77565"] },
  { name: "Cleveland", counties: ["Liberty", "Montgomery"], zipCodes: ["77327"] },
  { name: "Cloverleaf", counties: ["Harris"], zipCodes: ["77015"] },
  { name: "Clute", counties: ["Brazoria"], zipCodes: ["77531"] },
  { name: "Coldspring", counties: ["San Jacinto"], zipCodes: ["77331"] },
  { name: "Columbus", counties: ["Colorado"], zipCodes: ["78934"] },
  {
    name: "Conroe",
    counties: ["Montgomery"],
    zipCodes: ["77301", "77302", "77303", "77304", "77306", "77384", "77385"],
  },
  { name: "Cove", counties: ["Chambers"], zipCodes: ["77523"] },
  { name: "Crosby", counties: ["Harris"], zipCodes: ["77532"] },
  { name: "Crystal Beach", counties: ["Galveston"], zipCodes: ["77650"] },
  { name: "Cut and Shoot", counties: ["Montgomery"], zipCodes: ["77303", "77306"] },
  { name: "Cypress", counties: ["Harris"], zipCodes: ["77429", "77433"] },
  { name: "Daisetta", counties: ["Liberty"], zipCodes: ["77533"] },
  { name: "Damon", counties: ["Brazoria"], zipCodes: ["77430"] },
  { name: "Danbury", counties: ["Brazoria"], zipCodes: ["77534"] },
  { name: "Danciger", counties: ["Brazoria"], zipCodes: ["77431"] },
  { name: "Dayton", counties: ["Liberty"], zipCodes: ["77535"] },
  { name: "Dayton Lakes", counties: ["Liberty"], zipCodes: ["77535"] },
  { name: "Deer Park", counties: ["Harris"], zipCodes: ["77536"] },
  { name: "Devers", counties: ["Liberty"], zipCodes: ["77538"] },
  { name: "Dickinson", counties: ["Galveston"], zipCodes: ["77539"] },
  { name: "Eagle Lake", counties: ["Colorado"], zipCodes: ["77434"] },
  { name: "East Bernard", counties: ["Wharton"], zipCodes: ["77435"] },
  { name: "Edna", counties: ["Jackson"], zipCodes: ["77957"] },
  { name: "El Campo", counties: ["Wharton"], zipCodes: ["77437"] },
  { name: "El Lago", counties: ["Harris"], zipCodes: ["77586"] },
  { name: "Fairchilds", counties: ["Fort Bend"], zipCodes: ["77469"] },
  { name: "Fannett", counties: ["Jefferson"], zipCodes: ["77705"] },
  { name: "Four Corners", counties: ["Fort Bend", "Harris"], zipCodes: ["77083", "77498"] },
  { name: "Freeport", counties: ["Brazoria"], zipCodes: ["77541"] },
  { name: "Friendswood", counties: ["Galveston", "Harris"], zipCodes: ["77546"] },
  { name: "Fulshear", counties: ["Fort Bend"], zipCodes: ["77441"] },
  { name: "Galena Park", counties: ["Harris"], zipCodes: ["77547"] },
  { name: "Galveston", counties: ["Galveston"], zipCodes: ["77550", "77551", "77554"] },
  { name: "Ganado", counties: ["Jackson"], zipCodes: ["77962"] },
  { name: "Garwood", counties: ["Colorado"], zipCodes: ["77442"] },
  { name: "Gilchrist", counties: ["Galveston"], zipCodes: ["77617"] },
  { name: "Glen Flora", counties: ["Wharton"], zipCodes: ["77443"] },
  { name: "Goodrich", counties: ["Polk"], zipCodes: ["77335"] },
  { name: "Groves", counties: ["Jefferson"], zipCodes: ["77619"] },
  { name: "Hallettsville", counties: ["Lavaca"], zipCodes: ["77964"] },
  { name: "Hamshire", counties: ["Jefferson"], zipCodes: ["77622"] },
  { name: "Hankamer", counties: ["Chambers"], zipCodes: ["77560"] },
  { name: "Hardin", counties: ["Liberty"], zipCodes: ["77561"] },
  { name: "Hempstead", counties: ["Waller"], zipCodes: ["77445"] },
  { name: "High Island", counties: ["Galveston"], zipCodes: ["77623"] },
  { name: "Highlands", counties: ["Harris"], zipCodes: ["77562"] },
  { name: "Hillcrest", counties: ["Brazoria"], zipCodes: ["77511"] },
  { name: "Hitchcock", counties: ["Galveston"], zipCodes: ["77563"] },
  { name: "Holiday Lakes", counties: ["Brazoria"], zipCodes: ["77515"] },
  {
    name: "Houston",
    counties: ["Harris", "Fort Bend", "Montgomery"],
    zipCodes: [
      "77002",
      "77003",
      "77004",
      "77005",
      "77006",
      "77007",
      "77008",
      "77009",
      "77010",
      "77011",
      "77012",
      "77013",
      "77014",
      "77015",
      "77016",
      "77017",
      "77018",
      "77019",
      "77020",
      "77021",
      "77022",
      "77023",
      "77024",
      "77025",
      "77026",
      "77027",
      "77028",
      "77029",
      "77030",
      "77031",
      "77032",
      "77033",
      "77034",
      "77035",
      "77036",
      "77037",
      "77038",
      "77039",
      "77040",
      "77041",
      "77042",
      "77043",
      "77044",
      "77045",
      "77046",
      "77047",
      "77048",
      "77049",
      "77050",
      "77051",
      "77053",
      "77054",
      "77055",
      "77056",
      "77057",
      "77058",
      "77059",
      "77060",
      "77061",
      "77062",
      "77063",
      "77064",
      "77065",
      "77066",
      "77067",
      "77068",
      "77069",
      "77070",
      "77071",
      "77072",
      "77073",
      "77074",
      "77075",
      "77076",
      "77077",
      "77078",
      "77079",
      "77080",
      "77081",
      "77082",
      "77083",
      "77084",
      "77085",
      "77086",
      "77087",
      "77088",
      "77089",
      "77090",
      "77091",
      "77092",
      "77093",
      "77094",
      "77095",
      "77096",
      "77098",
      "77099",
    ],
  },
  { name: "Hull", counties: ["Liberty"], zipCodes: ["77564"] },
  { name: "Humble", counties: ["Harris"], zipCodes: ["77338", "77346", "77396"] },
  { name: "Hungerford", counties: ["Wharton"], zipCodes: ["77448"] },
  { name: "Huntsville", counties: ["Walker"], zipCodes: ["77320", "77340"] },
  { name: "Iago", counties: ["Wharton"], zipCodes: ["77448"] },
  { name: "Independence", counties: ["Washington"], zipCodes: ["77833"] },
  { name: "Iola", counties: ["Grimes"], zipCodes: ["77861"] },
  { name: "Iowa Colony", counties: ["Brazoria"], zipCodes: ["77583"] },
  { name: "Jacinto City", counties: ["Harris"], zipCodes: ["77029"] },
  { name: "Jamaica Beach", counties: ["Galveston"], zipCodes: ["77554"] },
  { name: "Jersey Village", counties: ["Harris"], zipCodes: ["77040", "77065"] },
  { name: "Jones Creek", counties: ["Brazoria"], zipCodes: ["77541"] },
  {
    name: "Katy",
    counties: ["Harris", "Fort Bend", "Waller"],
    zipCodes: ["77449", "77450", "77493", "77494"],
  },
  { name: "Kemah", counties: ["Galveston"], zipCodes: ["77565"] },
  { name: "Kendleton", counties: ["Fort Bend"], zipCodes: ["77451"] },
  { name: "Kenefick", counties: ["Liberty"], zipCodes: ["77535"] },
  { name: "Kingwood", counties: ["Harris", "Montgomery"], zipCodes: ["77339", "77345"] },
  { name: "Kountze", counties: ["Hardin"], zipCodes: ["77625"] },
  { name: "La Grange", counties: ["Fayette"], zipCodes: ["78945"] },
  { name: "La Marque", counties: ["Galveston"], zipCodes: ["77568"] },
  { name: "La Porte", counties: ["Harris"], zipCodes: ["77571"] },
  { name: "La Ward", counties: ["Jackson"], zipCodes: ["77970"] },
  { name: "Lake Jackson", counties: ["Brazoria"], zipCodes: ["77566"] },
  { name: "Lane City", counties: ["Wharton"], zipCodes: ["77453"] },
  { name: "League City", counties: ["Galveston", "Harris"], zipCodes: ["77573"] },
  { name: "Leggett", counties: ["Polk"], zipCodes: ["77350"] },
  { name: "Liberty", counties: ["Liberty"], zipCodes: ["77575"] },
  { name: "Liverpool", counties: ["Brazoria"], zipCodes: ["77577"] },
  { name: "Livingston", counties: ["Polk"], zipCodes: ["77351"] },
  { name: "Lolita", counties: ["Jackson"], zipCodes: ["77971"] },
  { name: "Louise", counties: ["Wharton"], zipCodes: ["77455"] },
  { name: "Lumberton", counties: ["Hardin"], zipCodes: ["77657"] },
  { name: "Magnolia", counties: ["Montgomery"], zipCodes: ["77354", "77355"] },
  { name: "Manvel", counties: ["Brazoria"], zipCodes: ["77578"] },
  { name: "Markham", counties: ["Matagorda"], zipCodes: ["77456"] },
  { name: "Matagorda", counties: ["Matagorda"], zipCodes: ["77457"] },
  { name: "Mauriceville", counties: ["Orange"], zipCodes: ["77626"] },
  { name: "Meadows Place", counties: ["Fort Bend"], zipCodes: ["77477"] },
  { name: "Missouri City", counties: ["Fort Bend", "Harris"], zipCodes: ["77459", "77489"] },
  { name: "Mont Belvieu", counties: ["Chambers", "Liberty"], zipCodes: ["77523"] },
  { name: "Montgomery", counties: ["Montgomery"], zipCodes: ["77316", "77356"] },
  { name: "Morgan's Point", counties: ["Harris"], zipCodes: ["77571"] },
  { name: "Nassau Bay", counties: ["Harris"], zipCodes: ["77058"] },
  { name: "Navasota", counties: ["Grimes"], zipCodes: ["77868"] },
  { name: "Nederland", counties: ["Jefferson"], zipCodes: ["77627"] },
  { name: "Needville", counties: ["Fort Bend"], zipCodes: ["77461"] },
  { name: "New Caney", counties: ["Montgomery"], zipCodes: ["77357"] },
  { name: "New Ulm", counties: ["Austin"], zipCodes: ["78950"] },
  { name: "New Waverly", counties: ["Walker"], zipCodes: ["77358"] },
  { name: "Nome", counties: ["Jefferson"], zipCodes: ["77629"] },
  { name: "North Cleveland", counties: ["Liberty"], zipCodes: ["77327"] },
  { name: "Oak Island", counties: ["Chambers"], zipCodes: ["77514"] },
  { name: "Oak Ridge North", counties: ["Montgomery"], zipCodes: ["77385"] },
  { name: "Oakhurst", counties: ["San Jacinto"], zipCodes: ["77359"] },
  { name: "Old Ocean", counties: ["Brazoria"], zipCodes: ["77463"] },
  { name: "Old River-Winfree", counties: ["Chambers", "Liberty"], zipCodes: ["77535"] },
  { name: "Onalaska", counties: ["Polk"], zipCodes: ["77360"] },
  { name: "Orange", counties: ["Orange"], zipCodes: ["77630", "77632"] },
  { name: "Orangefield", counties: ["Orange"], zipCodes: ["77639"] },
  { name: "Orchard", counties: ["Fort Bend"], zipCodes: ["77464"] },
  { name: "Oyster Creek", counties: ["Brazoria"], zipCodes: ["77541"] },
  { name: "Palacios", counties: ["Matagorda"], zipCodes: ["77465"] },
  { name: "Panorama Village", counties: ["Montgomery"], zipCodes: ["77304"] },
  {
    name: "Pasadena",
    counties: ["Harris"],
    zipCodes: ["77501", "77502", "77503", "77504", "77505", "77506", "77507"],
  },
  { name: "Pattison", counties: ["Waller"], zipCodes: ["77423"] },
  {
    name: "Pearland",
    counties: ["Brazoria", "Harris", "Fort Bend"],
    zipCodes: ["77581", "77584", "77588"],
  },
  { name: "Pecan Grove", counties: ["Fort Bend"], zipCodes: ["77406"] },
  { name: "Pine Island", counties: ["Waller"], zipCodes: ["77445"] },
  { name: "Pinehurst", counties: ["Orange"], zipCodes: ["77630"] },
  { name: "Plantersville", counties: ["Grimes"], zipCodes: ["77363"] },
  { name: "Pleak", counties: ["Fort Bend"], zipCodes: ["77469"] },
  { name: "Plum Grove", counties: ["Liberty"], zipCodes: ["77327"] },
  { name: "Point Blank", counties: ["San Jacinto"], zipCodes: ["77364"] },
  { name: "Point Comfort", counties: ["Calhoun"], zipCodes: ["77978"] },
  { name: "Port Arthur", counties: ["Jefferson"], zipCodes: ["77640", "77642"] },
  { name: "Port Bolivar", counties: ["Galveston"], zipCodes: ["77650"] },
  { name: "Port Neches", counties: ["Jefferson"], zipCodes: ["77651"] },
  { name: "Porter", counties: ["Montgomery"], zipCodes: ["77365"] },
  { name: "Prairie View", counties: ["Waller"], zipCodes: ["77446"] },
  { name: "Quintana", counties: ["Brazoria"], zipCodes: ["77541"] },
  { name: "Raywood", counties: ["Liberty"], zipCodes: ["77582"] },
  { name: "Richards", counties: ["Grimes"], zipCodes: ["77873"] },
  { name: "Richmond", counties: ["Fort Bend"], zipCodes: ["77406", "77407", "77469"] },
  { name: "Richwood", counties: ["Brazoria"], zipCodes: ["77531"] },
  { name: "Rock Island", counties: ["Colorado"], zipCodes: ["77470"] },
  { name: "Roman Forest", counties: ["Montgomery"], zipCodes: ["77357"] },
  { name: "Romayor", counties: ["Liberty"], zipCodes: ["77368"] },
  { name: "Rosenberg", counties: ["Fort Bend"], zipCodes: ["77469", "77471"] },
  { name: "Rosharon", counties: ["Brazoria", "Fort Bend"], zipCodes: ["77583"] },
  { name: "Round Top", counties: ["Fayette"], zipCodes: ["78954"] },
  { name: "Rye", counties: ["Liberty"], zipCodes: ["77369"] },
  { name: "San Felipe", counties: ["Austin"], zipCodes: ["77473"] },
  { name: "San Leon", counties: ["Galveston"], zipCodes: ["77539"] },
  { name: "Santa Fe", counties: ["Galveston"], zipCodes: ["77510"] },
  { name: "Saratoga", counties: ["Hardin"], zipCodes: ["77585"] },
  { name: "Seabrook", counties: ["Harris"], zipCodes: ["77586"] },
  { name: "Sealy", counties: ["Austin"], zipCodes: ["77474"] },
  { name: "Shenandoah", counties: ["Montgomery"], zipCodes: ["77380"] },
  { name: "Shepherd", counties: ["San Jacinto"], zipCodes: ["77371"] },
  { name: "Sheridan", counties: ["Colorado"], zipCodes: ["77475"] },
  { name: "Shoreacres", counties: ["Harris"], zipCodes: ["77571"] },
  { name: "Sienna", counties: ["Fort Bend"], zipCodes: ["77459"] },
  { name: "Silsbee", counties: ["Hardin"], zipCodes: ["77656"] },
  { name: "Simonton", counties: ["Fort Bend"], zipCodes: ["77476"] },
  { name: "Snook", counties: ["Burleson"], zipCodes: ["77878"] },
  { name: "Somerville", counties: ["Burleson"], zipCodes: ["77879"] },
  { name: "Sour Lake", counties: ["Hardin"], zipCodes: ["77659"] },
  { name: "South Houston", counties: ["Harris"], zipCodes: ["77587"] },
  { name: "Southside Place", counties: ["Harris"], zipCodes: ["77005"] },
  { name: "Splendora", counties: ["Montgomery"], zipCodes: ["77372"] },
  {
    name: "Spring",
    counties: ["Harris", "Montgomery"],
    zipCodes: ["77373", "77379", "77380", "77386", "77388", "77389"],
  },
  { name: "Spring Valley Village", counties: ["Harris"], zipCodes: ["77055"] },
  { name: "Stafford", counties: ["Fort Bend", "Harris"], zipCodes: ["77477"] },
  { name: "Stagecoach", counties: ["Montgomery"], zipCodes: ["77355"] },
  { name: "Stowell", counties: ["Chambers"], zipCodes: ["77661"] },
  { name: "Sugar Land", counties: ["Fort Bend"], zipCodes: ["77478", "77479", "77498"] },
  { name: "Surfside Beach", counties: ["Brazoria"], zipCodes: ["77541"] },
  { name: "Sweeny", counties: ["Brazoria"], zipCodes: ["77480"] },
  { name: "Taylor Lake Village", counties: ["Harris"], zipCodes: ["77586"] },
  { name: "Texas City", counties: ["Galveston"], zipCodes: ["77590", "77591"] },
  {
    name: "The Woodlands",
    counties: ["Montgomery", "Harris"],
    zipCodes: ["77380", "77381", "77382", "77384", "77385", "77386"],
  },
  { name: "Thompsons", counties: ["Fort Bend"], zipCodes: ["77481"] },
  { name: "Tiki Island", counties: ["Galveston"], zipCodes: ["77554"] },
  { name: "Todd Mission", counties: ["Grimes"], zipCodes: ["77363"] },
  { name: "Tomball", counties: ["Harris", "Montgomery"], zipCodes: ["77375", "77377"] },
  { name: "Van Vleck", counties: ["Matagorda"], zipCodes: ["77482"] },
  { name: "Vanderbilt", counties: ["Jackson"], zipCodes: ["77991"] },
  { name: "Vidor", counties: ["Orange"], zipCodes: ["77662"] },
  { name: "Wadsworth", counties: ["Matagorda"], zipCodes: ["77483"] },
  { name: "Waller", counties: ["Waller", "Harris"], zipCodes: ["77484"] },
  { name: "Wallis", counties: ["Austin"], zipCodes: ["77485"] },
  { name: "Wallisville", counties: ["Chambers"], zipCodes: ["77597"] },
  { name: "Washington", counties: ["Washington"], zipCodes: ["77880"] },
  { name: "Webster", counties: ["Harris"], zipCodes: ["77598"] },
  { name: "West Columbia", counties: ["Brazoria"], zipCodes: ["77486"] },
  { name: "West Orange", counties: ["Orange"], zipCodes: ["77630"] },
  { name: "West University Place", counties: ["Harris"], zipCodes: ["77005"] },
  { name: "Weston Lakes", counties: ["Fort Bend"], zipCodes: ["77441"] },
  { name: "Wharton", counties: ["Wharton"], zipCodes: ["77488"] },
  { name: "Wild Peach Village", counties: ["Brazoria"], zipCodes: ["77480"] },
  { name: "Willis", counties: ["Montgomery"], zipCodes: ["77318", "77378"] },
  { name: "Winnie", counties: ["Chambers", "Jefferson"], zipCodes: ["77665"] },
  { name: "Woodbranch", counties: ["Montgomery"], zipCodes: ["77357"] },
] as const satisfies readonly ServiceArea[];

export const LOCAL_FOCUS_NAMES = [
  "South Houston",
  "Pasadena",
  "Deer Park",
  "La Porte",
  "Pearland",
  "Brookside Village",
  "Friendswood",
  "Webster",
  "Clear Lake area",
  "Nassau Bay",
  "Seabrook",
  "Kemah",
  "League City",
  "Dickinson",
  "Santa Fe",
  "Alvin",
  "Manvel",
  "Iowa Colony",
  "Rosharon",
  "Liverpool",
] as const;

export const SERVICE_AREA_ZIPS: readonly ServiceAreaZip[] = Array.from(
  SERVICE_AREAS.reduce((byZip, area) => {
    for (const zipCode of area.zipCodes) {
      const entry = byZip.get(zipCode) ?? {
        communities: new Set<string>(),
        counties: new Set<string>(),
      };
      entry.communities.add(area.name);
      area.counties.forEach((county) => entry.counties.add(county));
      byZip.set(zipCode, entry);
    }
    return byZip;
  }, new Map<string, { communities: Set<string>; counties: Set<string> }>()),
  ([zipCode, entry]) => ({
    zipCode,
    communities: Array.from(entry.communities).sort((a, b) => a.localeCompare(b)),
    counties: Array.from(entry.counties).sort((a, b) => a.localeCompare(b)),
    group: `${zipCode.slice(0, 3)}xx`,
  }),
).sort((a, b) => Number(a.zipCode) - Number(b.zipCode));

export const ZIP_GROUPS = Array.from(new Set(SERVICE_AREA_ZIPS.map(({ group }) => group))).sort();

// South Houston and most of the south/southeast local-focus communities use 775 ZIPs.
export const DEFAULT_ZIP_GROUP = "775xx";

export const SERVICE_AREA_COUNTIES = Array.from(
  new Set(SERVICE_AREAS.flatMap(({ counties }) => counties)),
).sort((a, b) => a.localeCompare(b));
